# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOEDq89_r7EtLUD36Cw_lLwjkBiweXxE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             accuracy_score, roc_auc_score, roc_curve)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import warnings
warnings.filterwarnings('ignore')

print('✅ TensorFlow version:', tf.__version__)
print('✅ All libraries imported successfully!')

# Load dataset
data = load_breast_cancer()

# Create DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df['diagnosis'] = df['target'].map({0: 'Malignant', 1: 'Benign'})

print('📋 Dataset Info:')
print(f'   - Total samples  : {df.shape[0]}')
print(f'   - Total features : {df.shape[1] - 2}')
print(f'   - Classes        : {list(data.target_names)}')
print()
print('📈 Class Distribution:')
print(df['diagnosis'].value_counts())
print()
df.head()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

counts = df['diagnosis'].value_counts()
axes[0].pie(counts, labels=counts.index, autopct='%1.1f%%',
            colors=['#FF6B6B', '#4ECDC4'], startangle=90,
            textprops={'fontsize': 13})
axes[0].set_title('Class Distribution', fontsize=14, fontweight='bold')

sns.countplot(data=df, x='diagnosis', palette=['#FF6B6B', '#4ECDC4'], ax=axes[1])
axes[1].set_title('Sample Count per Class', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Diagnosis')
axes[1].set_ylabel('Count')
for p in axes[1].patches:
    axes[1].annotate(f'{int(p.get_height())}',
                     (p.get_x() + p.get_width() / 2., p.get_height()),
                     ha='center', va='bottom', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

# Fixed Cell 4 — Correlation Heatmap
top_features = df.corr(numeric_only=True)['target'].abs().sort_values(ascending=False)[1:11].index.tolist()

plt.figure(figsize=(12, 8))
corr_matrix = df[top_features + ['target']].corr(numeric_only=True)
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            mask=mask, linewidths=0.5, annot_kws={'size': 9})
plt.title('Correlation Heatmap — Top 10 Features vs Target', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print('✅ Data preprocessed successfully!')
print(f'   - Training set : {X_train_scaled.shape[0]} samples')
print(f'   - Testing set  : {X_test_scaled.shape[0]} samples')
print(f'   - Features     : {X_train_scaled.shape[1]}')

tf.random.set_seed(42)

model = keras.Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(64, activation='relu', name='hidden_1'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu', name='hidden_2'),
    layers.BatchNormalization(),
    layers.Dropout(0.2),
    layers.Dense(16, activation='relu', name='hidden_3'),
    layers.Dense(1, activation='sigmoid', name='output')
], name='ANN_BreastCancer')

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=15, restore_best_weights=True
)
reduce_lr = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.5, patience=7, min_lr=1e-6
)

history = model.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

print(f'\n✅ Training done at epoch: {len(history.history["loss"])}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['loss'], label='Train Loss', color='#FF6B6B', linewidth=2)
axes[0].plot(history.history['val_loss'], label='Val Loss', color='#4ECDC4', linewidth=2)
axes[0].set_title('Training & Validation Loss', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history.history['accuracy'], label='Train Accuracy', color='#FF6B6B', linewidth=2)
axes[1].plot(history.history['val_accuracy'], label='Val Accuracy', color='#4ECDC4', linewidth=2)
axes[1].set_title('Training & Validation Accuracy', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

y_pred_prob = model.predict(X_test_scaled, verbose=0).flatten()
y_pred      = (y_pred_prob >= 0.5).astype(int)

test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)
roc_auc = roc_auc_score(y_test, y_pred_prob)

print('=' * 50)
print('📊 ANN MODEL EVALUATION RESULTS')
print('=' * 50)
print(f'✅ Test Accuracy : {test_acc:.4f} ({test_acc*100:.2f}%)')
print(f'✅ Test Loss     : {test_loss:.4f}')
print(f'✅ ROC-AUC Score : {roc_auc:.4f}')
print('=' * 50)
print()
print('📋 Classification Report:')
print(classification_report(y_test, y_pred, target_names=['Malignant', 'Benign']))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Malignant', 'Benign'],
            yticklabels=['Malignant', 'Benign'],
            linewidths=1, linecolor='white', annot_kws={'size': 16})
axes[0].set_title('Confusion Matrix', fontsize=14, fontweight='bold')
axes[0].set_ylabel('Actual Label')
axes[0].set_xlabel('Predicted Label')

fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
axes[1].plot(fpr, tpr, color='#FF6B6B', linewidth=2.5, label=f'AUC = {roc_auc:.4f}')
axes[1].plot([0, 1], [0, 1], 'k--', linewidth=1.5, label='Random Classifier')
axes[1].fill_between(fpr, tpr, alpha=0.1, color='#FF6B6B')
axes[1].set_title('ROC Curve', fontsize=14, fontweight='bold')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend(fontsize=12)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print('🔮 Sample Predictions (first 10 from test set):')
print('-' * 65)
print(f'{"No":>4} | {"Actual":>12} | {"Predicted":>12} | {"Confidence":>12} | Status')
print('-' * 65)

label_map = {0: 'Malignant', 1: 'Benign'}
for i in range(10):
    actual    = label_map[y_test[i]]
    predicted = label_map[y_pred[i]]
    prob      = y_pred_prob[i] if y_pred[i] == 1 else 1 - y_pred_prob[i]
    status    = '✅ Correct' if y_test[i] == y_pred[i] else '❌ Wrong'
    print(f'{i+1:>4} | {actual:>12} | {predicted:>12} | {prob:>11.2%} | {status}')

print('-' * 65)